name: Optimize Images

on:
  push:
    paths:
      - '**.jpg'
      - '**.png'
      - '**.jpeg'

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Optimize images
        uses: calibreapp/image-actions@v1
        with:
          compress_only: true
          jpeg_quality: 80
          png_quality: 80
